import "./src/styles/main.css"
import "./src/styles/grid.css"
import "./src/styles/page.css"
// import "./src/styles/hero.css"
// import "./src/styles/about.css"
// import "./src/styles/skills.css"
// import "./src/styles/projects.css"
import "./src/styles/media.css"
